# Generated by Django 4.0.2 on 2022-03-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='update_desc',
            field=models.CharField(default='Placed', max_length=5000),
        ),
    ]
