# Generated by Django 4.0.2 on 2022-03-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders_update_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(default='Placed', max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('email', models.CharField(max_length=120)),
                ('items_json', models.CharField(max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='update_desc',
        ),
    ]
